get http://localhost:4266/stores/5cf38b414e1f131a68d8bbd8/videos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InJvbGVzIjpbInVzZXIiXSwiX2lkIjoiNWNmMzhiZDE3NDA3Y2E1ZmY4YWZlMThjIiwidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiJ0ZXN0Iiwic3RvcmUiOiI1Y2YzOGI0MTRlMWYxMzFhNjhkOGJiZDgiLCJqc29uIjp7fSwiY3JlYXRlZEF0IjoiMjAxOS0wNi0wMlQwODo0MTo1My40MTBaIiwidXBkYXRlZEF0IjoiMjAxOS0wNi0wMlQwODo0MTo1My40MTBaIiwiX192IjowfSwiaWQiOiI1Y2YzOGJkMTc0MDdjYTVmZjhhZmUxOGMiLCJpYXQiOjE1NTk0NjUwMjB9.qcFGEv-5sbLxcB9I5AX_FiJLrsRvSr47hoXB6d8XAJ8

{
    "json": {"fieldName":"file","originalFilename":"Capture.PNG","path":"assets\\uploads\\ytScSd_QUIgZmIrJEdjfT4wo.PNG","headers":{"content-disposition":"form-data; name=\"file\"; filename=\"Capture.PNG\"","content-type":"image/png"},"size":292300,"name":"Capture.PNG","type":"image/png"},
    "name": "assets\\uploads\\ytScSd_QUIgZmIrJEdjfT4wo.PNG",
    "username": "test",
    "password": "test",
    "store": "5cf38b414e1f131a68d8bb42"
}


# store id (test) 5cf38b414e1f131a68d8bbd8
# token (test) eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InJvbGVzIjpbInVzZXIiXSwiX2lkIjoiNWNmMzhiZDE3NDA3Y2E1ZmY4YWZlMThjIiwidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiJ0ZXN0Iiwic3RvcmUiOiI1Y2YzOGI0MTRlMWYxMzFhNjhkOGJiZDgiLCJqc29uIjp7fSwiY3JlYXRlZEF0IjoiMjAxOS0wNi0wMlQwODo0MTo1My40MTBaIiwidXBkYXRlZEF0IjoiMjAxOS0wNi0wMlQwODo0MTo1My40MTBaIiwiX192IjowfSwiaWQiOiI1Y2YzOGJkMTc0MDdjYTVmZjhhZmUxOGMiLCJpYXQiOjE1NTk0NjUwMjB9.qcFGEv-5sbLxcB9I5AX_FiJLrsRvSr47hoXB6d8XAJ8

###

post http://localhost:4266/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}
