
swagger: "2.0"
info:
    version: "0.0.1"
    title: "Swagger API"
host: localhost:4266
basePath: "/"
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
        

definitions:
    User:
        type: object
        properties:
            username:
                type: string
            password:
                type: string
            roles:
                type: array
                items:
                    type: string
            json:
                type: object
    UserCreateBody:
        type: object
        properties:
            username:
                type: string
            password:
                type: string
            json:
                type: object
    UserChangesBody:
        type: object
        properties:
            username:
                type: string
            password:
                type: string
            json:
                type: object
    UserPushBody:
        type: object
    UserPullBody:
        type: object
    UserUpdateBody:
        type: object
        properties:
            id:
                type: string
            changes:
                $ref: '#/definitions/UserChangesBody'
            push:
                $ref: '#/definitions/UserPushBody'
            pull:
                $ref: '#/definitions/UserPullBody'
    AddIdBody:
        type: object
        properties:
            addId:
                type: string
    AddIdsBody:
        type: object
        properties:
            addIds:
                type: array
                items:
                    type: string
    RemoveIdBody:
        type: object
        properties:
            addId:
                type: string
    RemoveIdsBody:
        type: object
        properties:
            addIds:
                type: array
                items:
                    type: string


paths:
    /users:
        get:
            description: "sample description"
            responses:
                '200':
                    description: "not provided."
                    schema:
                        type: object
        post:
            description: "sample description"
            parameters:
                - name: body
                  description: "Not provided"
                  in: body
                  schema:
                    $ref: '#/definitions/UserCreateBody'
            responses:
                '200':
                    description: "not provided."
                    schema:
                        type: object
    /users/{id}:
        get:
            description: "sample description"
            parameters:
                - name: id
                  in: path
                  required: true
                  description: "Not provided"
                  type: string
            responses:
                '200':
                    description: "not provided."
                    schema:
                        type: object
        put:
            description: "sample description"
            parameters:
                - name: id
                  in: path
                  required: true
                  description: "Not provided"
                  type: string

                - name: body
                  description: "Not provided"
                  in: body
                  schema:
                    $ref: '#/definitions/UserUpdateBody'
            responses:
                '200':
                    description: "not provided."
                    schema:
                        type: object

